import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['100', '300','400', '500', '600', '700', '800'],
  variable: '--font-league-spartan', // Variável CSS personalizada
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={leagueSpartan.variable}>
      <body className="font-sans">
        {children}
      </body>
    </html>
  )
}
