import type { Metadata } from "next";
<<<<<<< HEAD
import { League_Spartan } from "next/font/google";
=======
import { Geist, Geist_Mono, Inter } from "next/font/google";
>>>>>>> b756be2 (Atualiza frontend)
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/marcuscomp/Sidebar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['100', '300','400', '500', '600', '700', '800'],
  variable: '--font-league-spartan', // Variável CSS personalizada
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<<<<<<< HEAD
    <html lang="pt-BR" className={leagueSpartan.variable}>
      <body className="font-sans">
        {children}
=======
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-dvh bg-[#d9d9d9]">
        <div className="flex min-h-dvh">
          <Sidebar />
          <main className="flex-1">{children}</main>
        </div>
>>>>>>> b756be2 (Atualiza frontend)
      </body>
    </html>
  )
}
